### ISSUE TITLE
Fusão OPENWRT e LEDE

### ISSUE THREAD

**Issue by farribeiro** [simetnicbr/simetbox-openwrt-base#10]
Da nota do BR-Linux: https://br-linux.org/2018/01/anunciada-a-unificacao-do-openwrt-e-lede.html

<blockquote>
<p>Forks são comuns no universo FOSS. Discordâncias técnicas e até
mesmo filosóficas, ou implicância entre membros podem gerar
novos projetos. E as vezes fica complicado julgar quando um fork
foi útil, ou gerou apenas mais software no mundo. A exemplo do
que aconteceu com o <a
href="https://br-linux.org/2014/01/lxqt-o-novo-ambiente-grafico-desktop-criado-pela-combinacao-do-lxde-e-razor-qt.html">LXQt</a>,
onde dois projetos de matéria convergente, os projetos LEDE e
OpenWrt anunciaram a reunificação após <a
href="https://lwn.net/Articles/722135/">alguns meses
negociação</a>.</p>
<p>Ambos projetos estão felizes em anunciar esta manobra, que
exigiu um trabalho árduo para levantar as questões específicas
da reunificação, e que teve muitas propostas e poucas ações. A
nova e unificada versão do OpenWrt será governada pelas <a
href="https://lede-project.org/rules">regras estabelecidas</a>
pelo projeto LEDE. Membros ativos de ambos os projetos
continuarão a trabalhar na versão unificada do OpenWrt. </p>
<p>O Fork LEDE e seu merge de volta ao OpenWrt não alterará a
direção técnica adotada pela unificação dos projetos. A busca
por estabilidade e lançamentos de manutenção ao mesmo tempo que
lançamentos menores são executado para endereçar bugs críticos e
incidentes de segurança, continuará funcionando nos mesmo moldes
do que foi feito com o LEDE 17.01. </p>
<p>Versões anteriores ao OpenWrt 15.05 CC(chaos calmer) não serão
suportadas pelo merge, e serão abandonadas sem atualizações de
segurança e estabilidade. A versão OpenWrt 15.05 CC receberá uma
quantidade limitada de correções de segurança, e não estará
totalmente integrada ao esquema de automatização de lançamentos,
fazendo com que os binários demorem um pouco mais a serem
lançados. O LEDE 17.01 continuará a receber suporte contínuo a
correções de estabilidade e segurança para os binários e fontes.
Em breve haverá uma nova versão disponível. </p>
<p>O projeto unificado irá utilizar a base de códigos-fonte do
LEDE. Patches específicos do OpenWrt que atingirem os critérios
de qualidade impostos pelo LEDE serão integrados a árvore. O
código-fonte será hospedado em <a
href="https://git.openwrt.org">git.openwrt.org</a> e terá um
espelhamento no <a href="https://github.com/openwrt/openwrt">Github</a>.
O código original do OpenWrt será <a
href="https://github.com/openwrt/archive">arquivado no Github</a>
para referências futuras. Pull requests para os repositórios do
OpenWrt e LEDE atuais serão fechados após um período de 30 dias.
É encorajado as pessoas que possuem patches pendentes que corram
atrás para que tenham seus trabalhos aplicados na árvore.</p>
<p>A reunificação do projeto OpenWrt é representada pela <a
href="https://www.spi-inc.org/">SPI(Software in the Public
Interest)</a>, uma organização sem fins lucrativos US
501(c)(3) que está gerenciando o <a
href="https://www.spi-inc.org/projects/openwrt/">registro da
marca OpenWrt</a>, as doações para o projeto, e auxiliando as
questões legais envolvidas no processo.</p>
<p>A infraestrutura disponível atualmente no domínio
lede-project.org será movida ao domínio openwrt.org e
redirecionamentos serão configurados onde for apropriado. O que
será feito com fóruns e wikis de ambos os projetos ainda não foi
decidido, ficando em seus domínios até que um consenso seja
atingido.</p>
<p>Para matéria na íntegra, acesse o link de referência, e para
aqueles desconhecem a história por trás da separação dos
projetos a cerca de 1 ano e meio atrás, <a
href="https://lwn.net/Articles/686767/">o seguinte link</a> é
uma boa compilação de todos os eventos.<a
href="https://forum.lede-project.org/t/announcing-the-openwrt-lede-merge/">Referência:
forum.lede-project.org</a></p>
</blockquote>

**Comment by hmh** [comment]
Até onde o código fonte vai, a fusão está completa.  Estamos trabalhando na SIMETBOX já baseados no que chamo OpenWRT 2018 por falta de um nome melhor até o momento...

**Comment by farribeiro** [comment]
Link to issue https://github.com/simetnicbr/simetbox-openwrt-feed/issues/4
