### ISSUE TITLE
Reiniciar não funciona em alguns equipamentos em versões antigas

### ISSUE THREAD

**Issue by LeoFCardoso** [simetnicbr/simetbox-openwrt-base#5]
TP-LINK WDR4300 V1
Build 07-Apr-2017 19:15
------
Opção 'Sistema / Reiniciar' não reinicia efetivamente o Simetbox (nada acontece).

Fica sempre na tela:

Reiniciar
Reinicia o sistema operacional do seu dispositivo
Por favor aguarde: Equipamento reiniciando...

**Comment by tamusiunas** [comment]
Esta é uma opção referente ao OpenWRT/LEDE e não tem relação direta com o SIMETBox.
Qual a distribuição/versão está em uso (OpenWRT ou LEDE/versão)?

**Comment by LeoFCardoso** [comment]
Firmware baixado em https://simet.nic.br/firmware/
Build 07-Apr-2017 19:15

**Comment by tamusiunas** [comment]
Vou dar uma conferida nisto. É possível sim que esteja com algum problema deste tipo. O firmware que está lá ainda é um firmware muito personalizado. Na próxima semana trocaremos pela versão OpenSource usando o OpenWRT 15 e LEDE. Assim que trocarmos ele, publico aqui neste thread.

**Comment by farribeiro** [comment]
Questiono, essa dúvida já foi sanada? Gentileza, fechar!

**Comment by hmh** [comment]
FWIW, funciona no OpenWRT LEDE-17.01, e funciona no OpenWRT 18.06-SNAPSHOT.

**Comment by farribeiro** [comment]
Como disse anteriormente, na issue #4. O autor tem a iniciativa de finalizar.

**Comment by LeoFCardoso** [comment]
Deixo a vosso critério. Infelizmente não disponho mais do ambiente. Abraço a todos.

**Comment by farribeiro** [comment]
Encerrem tal issue

@tamusiunas ok?
@hmh ok?

**Comment by hmh** [comment]
O bug foi reproduzido em laboratório, mas existe apenas nesse hardware (não existe, por exemplo, nas TL-WR842ND) e em versões antigas do OpenWRT (não existe mais nas versões atuais dos _branches_ lede-17.01, master e openwrt-18.6 para a TL-WDR4300).
